function on_game_start()
	RegisterScriptCallback("on_npc_sound_init", this.on_npc_sound_init)
	RegisterScriptCallback("on_npc_sound_play", this.on_npc_sound_play)
	RegisterScriptCallback("on_actor_sound_init", this.on_actor_sound_init)
	RegisterScriptCallback("on_actor_sound_play", this.on_actor_sound_play)
	RegisterScriptCallback("on_object_sound_init", this.on_object_sound_init)
	RegisterScriptCallback("on_object_sound_play", this.on_object_sound_play)
	RegisterScriptCallback("on_trader_sound_play", this.on_trader_sound_play)
	RegisterScriptCallback("on_trader_sound_end", this.on_trader_sound_end)
end

--------------------------------------------------------

-- NPC (type = npc):
function on_npc_sound_init(ref_binder, snd_ini, section)
    ref_binder.subs           = utils.cfg_get_bool(snd_ini, section, "subtitles", nil, false, subtitles.CONFIG.DEF_NPC_SUBS)
	ref_binder.subs_name      = utils.cfg_get_string(snd_ini, section, "subtitles_name", nil, false, "", "")
	ref_binder.subs_text      = utils.cfg_get_string(snd_ini, section, "subtitles_text", nil, false, "", "")
	ref_binder.subs_distance  = utils.cfg_get_number(snd_ini, section, "subtitles_distance", nil, false, subtitles.CONFIG.MAX_DISTANCE)
	ref_binder.subs_delay  	  = utils.cfg_get_number(snd_ini, section, "subtitles_delay", nil, false, subtitles.CONFIG.SHOW_DELAY)

	ref_binder.ws_subs        = utils.cfg_get_bool(snd_ini, section, "ws_subtitles", nil, false, subtitles.WS_CONFIG.DEF_NPC_SUBS)
    ref_binder.ws_section     = utils.cfg_get_string(snd_ini, section, "ws_subtitles_section", nil, false, "", subtitles.WS_CONFIG.DEF_WS_SECTION)
	ref_binder.ws_subs_text   = utils.cfg_get_string(snd_ini, section, "ws_subtitles_text", nil, false, "", "")
	ref_binder.ws_subs_delay  = utils.cfg_get_number(snd_ini, section, "ws_subtitles_delay", nil, false, subtitles.WS_CONFIG.SHOW_DELAY)
end

function on_npc_sound_play(ref_binder, npc_id, faction, point, msg)
    if ref_binder.subs then
        local snd = ref_binder.sound_path[npc_id][ref_binder.played_id + 1]
		local name = level.object_by_id(npc_id):character_name()
		local text = snd:gsub("\\", "_")
		local delay = ref_binder.subs_delay

        if ref_binder.subs_name and ref_binder.subs_name ~= "" then
			name = ref_binder.subs_name
		end
		if ref_binder.subs_text and ref_binder.subs_text ~= "" then
			text = ref_binder.subs_text
		else
			if game.translate_string(text) == text then
				if not text:find("characters_voice_scenario_") then
					text = text:match("human_%d%d_(.*)")
				end
			end
		end

		if ref_binder.delay_sound > 0 and ref_binder.subs_delay == 0 then
			delay = ref_binder.delay_sound
		end

		subtitles.add_subtitles_npc(npc_id, name, text, delay, ref_binder.subs_distance)
    end

    if ref_binder.ws_subs then
		local snd = ref_binder.sound_path[npc_id][ref_binder.played_id + 1]
        local text = snd:gsub("\\", "_")
		local delay = ref_binder.ws_subs_delay

        if ref_binder.ws_subs_text and ref_binder.ws_subs_text ~= "" then
            text = ref_binder.ws_subs_text
		else
			if game.translate_string(text) == text then
				if not text:find("characters_voice_scenario_") then
					text = text:match("human_%d%d_(.*)")
				end
			end
        end

		if ref_binder.delay_sound > 0 and ref_binder.ws_subs_delay == 0 then
			delay = ref_binder.delay_sound
		end

        subtitles.add_ws_subtitles_npc(npc_id, ref_binder.ws_section, text, delay)
	end
end

-- ACTOR (type = actor):
function on_actor_sound_init(ref_binder, snd_ini, section)
	ref_binder.subs        = utils.cfg_get_bool(snd_ini, section, "subtitles", nil, false, subtitles.CONFIG.DEF_ACTOR_SUBS)
	ref_binder.subs_name   = utils.cfg_get_string(snd_ini, section, "subtitles_name", nil, false, "", "")
	ref_binder.subs_text   = utils.cfg_get_string(snd_ini, section, "subtitles_text", nil, false, "", "")
	ref_binder.subs_delay  = utils.cfg_get_number(snd_ini, section, "subtitles_delay", nil, false, subtitles.CONFIG.SHOW_DELAY)
end

function on_actor_sound_play(ref_binder, npc, faction, point, msg)
    if ref_binder.subs then
        local snd = ref_binder.sound[ref_binder.played_id]
        local name = db.actor:character_name()
		local text = snd:gsub("\\", "_")

        if ref_binder.subs_name and ref_binder.subs_name ~= "" then
			name = ref_binder.subs_name
		end
		if ref_binder.subs_text and ref_binder.subs_text ~= "" then
			text = ref_binder.subs_text
		else
			if game.translate_string(text) == text then
				if not text:find("characters_voice_scenario_") then
					text = text:match("human_%d%d_(.*)")
				end
			end
		end

        subtitles.add_subtitles_actor(name, text, ref_binder.snd_obj, ref_binder.subs_delay)
	end
end

-- OBJ (type = 3d):
function on_object_sound_init(ref_binder, snd_ini, section)
    ref_binder.subs           = utils.cfg_get_bool(snd_ini, section, "subtitles", nil, false, subtitles.CONFIG.DEF_OBJ_SUBS)
	ref_binder.subs_name      = utils.cfg_get_string(snd_ini, section, "subtitles_name", nil, false, "", "")
	ref_binder.subs_text      = utils.cfg_get_string(snd_ini, section, "subtitles_text", nil, false, "", "")
	ref_binder.subs_distance  = utils.cfg_get_number(snd_ini, section, "subtitles_distance", nil, false, subtitles.CONFIG.MAX_DISTANCE)
	ref_binder.subs_delay  	  = utils.cfg_get_number(snd_ini, section, "subtitles_delay", nil, false, subtitles.CONFIG.SHOW_DELAY)

	ref_binder.ws_subs        = utils.cfg_get_bool(snd_ini, section, "ws_subtitles", nil, false, subtitles.WS_CONFIG.DEF_OBJ_SUBS)
    ref_binder.ws_section     = utils.cfg_get_string(snd_ini, section, "ws_subtitles_section", nil, false, "", subtitles.WS_CONFIG.DEF_WS_SECTION)
	ref_binder.ws_subs_text   = utils.cfg_get_string(snd_ini, section, "ws_subtitles_text", nil, false, "", "")
	ref_binder.ws_subs_delay  = utils.cfg_get_number(snd_ini, section, "ws_subtitles_delay", nil, false, subtitles.WS_CONFIG.SHOW_DELAY)
end

function on_object_sound_play(ref_binder, obj_id, faction, point, msg)
    if ref_binder.subs then
        local snd = ref_binder.sound[ref_binder.played_id]
		local name = level.object_by_id(obj_id):name()
		local text = snd:gsub("\\", "_")

        if ref_binder.subs_name and ref_binder.subs_name ~= "" then
			name = ref_binder.subs_name
		end
		if ref_binder.subs_text and ref_binder.subs_text ~= "" then
			text = ref_binder.subs_text
		else
			if game.translate_string(text) == text then
				if not text:find("characters_voice_scenario_") then
					text = text:match("human_%d%d_(.*)")
				end
			end
		end

		subtitles.add_subtitles_obj(obj_id, name, text, ref_binder.snd_obj, ref_binder.subs_delay, ref_binder.subs_distance)
    end

    if ref_binder.ws_subs then
		local snd = ref_binder.sound[ref_binder.played_id]
        local text = snd:gsub("\\", "_")

        if ref_binder.ws_subs_text and ref_binder.ws_subs_text ~= "" then
            text = ref_binder.ws_subs_text
		else
			if game.translate_string(text) == text then
				if not text:find("characters_voice_scenario_") then
					text = text:match("human_%d%d_(.*)")
				end
			end
        end

        subtitles.add_ws_subtitles_obj(ref_binder.snd_obj, obj_id, ref_binder.ws_section, text, ref_binder.ws_subs_delay)
	end
end

-- TRADER (sidor, forester)
function on_trader_sound_play(ref_binder, snd)
	local name = ref_binder.object:character_name()
	local text = snd:gsub("\\", "_")

	subtitles.trader_is_playing = true
	subtitles.add_subtitles_trader(ref_binder.object:id(), name, text, subtitles.CONFIG.SHOW_DELAY, subtitles.CONFIG.MAX_DISTANCE)
end

function on_trader_sound_end()
	subtitles.trader_is_playing = false
end